apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: todo-django:latest
        ports:
        - containerPort: 8000
