apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: todo-app
spec:
  selector:
    app: todo
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
